<?
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G7"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["G6"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>