<?
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["obyavleniya"]["8"]="W";
$PERM["bitrix"]["8"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["G6"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G7"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["/"]["*"]="R";
?>